# Generated by Django 4.1.5 on 2023-02-08 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "separator",
                    models.CharField(
                        choices=[
                            (",", "Comma (,)"),
                            (" ", "Blank space ( )"),
                            (";", "Comma with dot (;)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "string_character",
                    models.CharField(
                        choices=[
                            ('"', 'Double quotes (")'),
                            ("'", "Single quotes (')"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modified", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataSets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Ready", "READY"), ("Processing", "PROCESSING")],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(null=True, upload_to="media")),
                ("number_for_this_schema", models.PositiveIntegerField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="csv_generator.schema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Columns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full name", "Full name"),
                            ("Job", "Job"),
                            ("Email", "Email"),
                            ("Domain name", "Domain name"),
                            ("Phone number", "Phone number"),
                            ("Company", "Company"),
                            ("Text", "Text"),
                            ("Integer", "Integer"),
                            ("Address", "Address"),
                            ("Date", "Date"),
                        ],
                        max_length=50,
                    ),
                ),
                ("min_value", models.IntegerField(blank=True, null=True)),
                ("max_value", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="csv_generator.schema",
                    ),
                ),
            ],
        ),
    ]
